---
- name: push unicorn init script
  template: src=unicorn_maalify.j2 dest=/etc/init.d/unicorn_maalify mode=755
  notify: Start Unicorn

- name: create target folder for database.yml
  file:
    path: "/opt/www/maalify/shared/config/"
    state: directory
    recurse: yes

- name: push database.yml to host
  template: src=database.yml.j2 dest={{ maalify_shared }}/config/database.yml

- name: push database.yml to host
  template: src=rbenv-vars.j2 dest={{ maalify_shared }}/.rbenv-vars

- name: push application.yml to host
  template: src=application.j2 dest={{ maalify_shared }}/application.yml

- name: push reboot.sh file to host
  template: src=reboot.sh.j2 dest=/root/reboot.sh mode=755

- name: add reboot job to cronjob
  cron:
    name: "a job for reboot"
    special_time: reboot
    job: "/root/reboot.sh"

- name: Start Unicorn on reboot
  lineinfile:
    dest=/etc/rc.local
    line='cd /opt/www/maalify/current && RAILS_ENV=production bundle exec unicorn -E production -c config/unicorn.rb -D'
    state=absent