---
- name: Download rbenv from github
  git: repo=https://github.com/sstephenson/rbenv.git
       dest=~/.rbenv

- name: Add rbenv-build plugin to rbenv
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build

- name: Add rbenv-vars plugin to rbenv
  git: repo=https://github.com/sstephenson/rbenv-vars.git
       dest=~/.rbenv/plugins/rbenv-vars

- name: add env variables to system profile.d
  blockinfile:
    dest: /etc/profile.d/rbenv.sh
    create: yes
    state: present
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: add path to rbenv in .bashrc file
  lineinfile:
    dest=~/.bashrc
    line='export PATH="$HOME/.rbenv/bin:$PATH"'
    state=present

- name: add rbenv to .bashrc file
  lineinfile:
    dest=~/.bashrc
    line='eval "$(rbenv init -)"'
    state=present

- name: source the bashrc file
  shell: source /root/.bashrc
  args:
      executable: /bin/bash

- name: add no doc for gem config
  lineinfile:
    dest=~/.gemrc
    line="gem{{':'}} --no-ri --no-rdoc"
    create=yes
    state=present

- name: install rbenv {{ ruby_version }}
  shell: /bin/bash /root/.rbenv/bin/rbenv install {{ ruby_version }} --skip-existing
  args:
      executable: /bin/bash

- name: use ruby version {{ ruby_version }}
  shell: /bin/bash /root/.rbenv/bin/rbenv global {{ ruby_version }}
  args:
      executable: /bin/bash
  notify: rbenv rehash

- name: Install Bundler
  shell: /root/.rbenv/shims/gem install bundler
  notify: rbenv rehash

- name: Install backup gem
  shell: /root/.rbenv/shims/gem install backup
  notify: rbenv rehash

